common: &common
  adapter: postgresql
  host: localhost

development:
  <<: *common
  database: voluntariando_me_development

test:
  <<: *common
  database: voluntariando_me_test

production:
  <<: *common
  database: voluntariando_me_production